# See help here: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-and-disabling-version-updates

version: 2
updates:
  # Enable version updates for Python API
  - package-ecosystem: pip
    directory: "/src/bindings/python"
    schedule:
      interval: weekly
      day: sunday
      time: "13:00"
    open-pull-requests-limit: 0
    reviewers:
      - jiwaszki
      - akuporos
    labels:
      - "category: dependencies"
