name: Documentation
on:
  pull_request:
  merge_group:

env:
  DOXY_VER: '1.9.6'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

permissions: read-all

jobs:
  Build_Doc:
    runs-on: ubuntu-22.04
    if: ${{ github.repository_owner == 'openvinotoolkit' }}
    steps:
      - name: Clone OpenVINO
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        timeout-minutes: 15
        with:
          submodules: 'true'
          lfs: 'true'

      - name: Install apt-get dependencies
        uses: awalsh128/cache-apt-pkgs-action@5902b33ae29014e6ca012c5d8025d4346556bd40 # v1.4.3
        with:
          packages: graphviz texlive liblua5.2-0 libclang1-9 libclang-cpp9
          version: 3.0

      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        id: cp310
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: |
            docs/requirements.txt
            docs/openvino_sphinx_theme/setup.py

      - name: Install python dependencies
        run: |
          python3 -m pip install -r docs/requirements.txt
          (cd docs/openvino_sphinx_theme && python3 -m pip install .)
          python3 -m pip install docs/openvino_custom_sphinx_sitemap

      - name: Download and install doxygen
        run: |
          # install doxygen
          wget https://www.doxygen.nl/files/doxygen-$DOXY_VER.linux.bin.tar.gz
          tar -I pigz -xf doxygen-$DOXY_VER.linux.bin.tar.gz
          echo "$(pwd)/doxygen-$DOXY_VER/bin/" >> $GITHUB_PATH

      - name: Validate benchmarks files
        run: |
          python3 docs/scripts/tests/validate_benchmarks.py  docs/sphinx_setup/_static/benchmarks_files/

      - name: Build docs
        run: |
          rm -rf build && mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DENABLE_DOCS=ON
          cmake --build . --target sphinx_docs

      - name: Cache documentation
        id: cache_sphinx_docs
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: build/docs/_build/.doctrees
          key: sphinx-docs-cache

      - name: Archive docs HTML
        run: (cd build/docs && zip -r openvino_docs_html.zip _build)

      - name: Set PR number
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

      - name: 'Upload sphinx.log'
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: sphinx_build_log_${{ env.PR_NUMBER }}.log
          path: build/docs/sphinx.log

      - name: 'Upload docs html'
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: openvino_docs_html_${{ env.PR_NUMBER }}.zip
          path: build/docs/openvino_docs_html.zip

      - name: Run Pytest
        run: |
          pytest --sphinx="./build/docs/sphinx.log" \
                 --suppress-warnings="./docs/scripts/tests/suppress_warnings.txt" \
                 --confcutdir="./docs/scripts/tests/" \
                 --html="./build/docs/_artifacts/doc-generation.html" \
                 --sphinx-strip="$(pwd)/build/docs/sphinx_source" \
                 --xfail="./docs/scripts/tests/xfail.txt" \
                 --self-contained-html ./docs/scripts/tests/test_docs.py

      - name: 'Upload test results'
        if: failure()
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: openvino_docs_pytest
          path: build/docs/_artifacts/
