name: PR Commits
on: [pull_request]

permissions: read-all

jobs:
  Checks:
    runs-on: ubuntu-22.04
    if: ${{ github.repository_owner == 'openvinotoolkit' }}
    steps:
      - name: Clone OpenVINO
        uses: ababushk/checkout@9bec46a94a83db82acd4303e7627d88db71402a5 # cherry_pick_retries
        timeout-minutes: 15

      - name: Install dependencies
        run: python3 -m pip install -r ./.github/github_org_control/requirements.txt

      - name: PR commits
        run: python3 ./.github/github_org_control/check_pr.py --pr=${{ github.event.number }} --check-commits DRY_RUN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
