name: Code snippets
on:
  push:
    paths:
      - '.github/workflows/code_snippets.yml'
      - 'docs/snippets/**'
    branches:
      - 'master'
      - 'releases/**'
  pull_request:
    paths:
      - '.github/workflows/code_snippets.yml'
      - 'docs/snippets/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-22.04', 'macos-latest', 'windows-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone OpenVINO
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          submodules: 'true'

      - name: Install OpenCL
        uses: awalsh128/cache-apt-pkgs-action@a6c3917cc929dd0345bfb2d3feaf9101823370ad # v1.4.2
        if: runner.os == 'Linux'
        with:
          packages: ocl-icd-opencl-dev opencl-headers
          version: 3.0

      - name: Install scons
        if: runner.os == 'macOS'
        run: brew install scons

      - name: CMake configure
        run: cmake -DCMAKE_BUILD_TYPE=Release -DTHREADING=SEQ -B build

      - name: Build snippets
        run:  cmake --build build --target openvino_docs_snippets --parallel
