name: 'Dependency Review'
on: [pull_request, merge_group]

permissions: read-all

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'openvinotoolkit' }}
    steps:
      - name: Clone OpenVINO
        uses: ababushk/checkout@9bec46a94a83db82acd4303e7627d88db71402a5 # cherry_pick_retries
        timeout-minutes: 15

      - name: Dependency Review
        uses: actions/dependency-review-action@05fe4576374b728f0c523d6a13d64c25081e0803 # v4.8.3
        with:
          config-file: './.github/dependency_review.yml'
          base-ref: ${{ github.event.pull_request.base.sha || github.event.merge_group.base_ref }}
          head-ref: ${{ github.event.pull_request.head.sha || github.ref }}
