name: 'Dependency Review'
on: [pull_request, merge_group]

permissions: read-all

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'openvinotoolkit' }}
    steps:
      - name: Clone OpenVINO
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        timeout-minutes: 15

      - name: Dependency Review
        uses: actions/dependency-review-action@da24556b548a50705dd671f47852072ea4c105d9 # v4.7.1
        with:
          config-file: './.github/dependency_review.yml'
          base-ref: ${{ github.event.pull_request.base.sha || github.event.merge_group.base_ref }}
          head-ref: ${{ github.event.pull_request.head.sha || github.ref }}
