name: Files Size
on: [push, pull_request]

jobs:
  Check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: git ls-tree
        run: |
          git ls-tree -r -t -l --full-name HEAD | sort -n -r -k 4

      - name: git lfs ls-files
        run: |
          git lfs ls-files --size

#      - uses: actionsdesk/lfs-warning@v1.1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          filesizelimit: '10' # 10 MB is 10485760 Bytes
