name: MO
on:
  push:
    paths:
      - 'model-optimizer/**'
  pull_request:
    paths:
      - 'model-optimizer/**'

jobs:
  Pylint-UT:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Cache pip
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('model-optimizer/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

        # tensorflow 1.15 causes modules import
        # errors, most likely due to https://github.com/PyCQA/pylint/issues/2603
        # for tensorflow.core.framework and tensorflow.contrib
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          # For UT
          pip install unittest-xml-reporting==3.0.2
          # MO requirements
          pip install -r requirements.txt
          pip install -r requirements_dev.txt
          # requrements for CMake
          sudo apt --assume-yes install libusb-1.0-0-dev libprotobuf-dev
        working-directory: model-optimizer

      - name: Pylint
        run: pylint -d C,R,W mo/ mo.py extensions/
        working-directory: model-optimizer

      - name: CMake
        run: |
          mkdir build
          cd build
          cmake ..

      - name: UT
        run: |
          export PYTHONPATH=$PYTHONPATH:`pwd`
          export MO_ROOT=`pwd`
          env
          mkdir ../mo-ut-logs
          python3 -m xmlrunner discover -p *_test.py --output=../mo-ut-logs
        working-directory: model-optimizer
  
  build_wheel:
    name: Build Python wheel
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install wheel setuptools
          python3 -m pip install tensorflow==2.3.0
      
      - name: Build
        run: |
          python3 setup.py sdist bdist_wheel
        working-directory: model-optimizer
      
      - name: Test package content
        run: |
          echo "src = open('openvino_mo.egg-info/SOURCES.txt', 'rt').read().split()" | tee -a test_wheel.py
          echo "ref = open('automation/package_BOM.txt', 'rt').read().split()"       | tee -a test_wheel.py
          echo "for name in ref:"                                                    | tee -a test_wheel.py
          echo "  if name.endswith('.py'):"                                          | tee -a test_wheel.py
          echo "    assert name in src or './' + name in src, name + ' file missed'" | tee -a test_wheel.py
          python3 test_wheel.py
        working-directory: model-optimizer

      - name: Test conversion
        run: |
          wget -q http://download.tensorflow.org/models/mobilenet_v1_2018_08_02/mobilenet_v1_1.0_224.tgz
          tar -xf mobilenet_v1_1.0_224.tgz
          python3 -m pip install model-optimizer/dist/*.whl
          python3 -m mo --input_model mobilenet_v1_1.0_224_frozen.pb --input_shape "[1,224,224,3]"

      - uses: actions/upload-artifact@v2
        with:
          name: mo_wheel
          path: "model-optimizer/dist/*.whl"
