name: MO
on:
  push:
    paths:
      - 'tools/mo/**'
      - '.github/workflows/mo.yml'
    branches:
      - 'master'
      - 'releases/**'
  pull_request:
    paths:
      - 'tools/mo/**'
      - '.github/workflows/mo.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  Pylint-UT:
    runs-on: ubuntu-22.04
    if: ${{ github.repository_owner == 'openvinotoolkit' }}
    steps:
      - name: Clone OpenVINO
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Setup Python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@3624ceb22c1c5a301c8db4169662070a689d9ea8 # v4.1.1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('tools/mo/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          # For UT
          pip install unittest-xml-reporting==3.0.2
          # MO requirements
          pip install -r requirements_caffe.txt
          pip install -r requirements_kaldi.txt
          pip install -r requirements_onnx.txt
          pip install -r requirements_tf2.txt
          pip install -r requirements_dev.txt
        working-directory: tools/mo

      - name: Pylint-MO
        run: pylint -d C,R,W openvino/tools/mo
        working-directory: tools/mo
